---
-
  name: 'Ajax Form Endpoint'
  uriPattern: '__form/{formIdentifier}/{presetName}(/{locale})'
  defaults:
    '@package': 'Onedrop.AjaxForm'
    '@controller': 'AjaxForm'
    '@action': 'index'
    '@format': 'html'
    'locale': ''
  httpMethods: ['GET','POST']
