Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Onedrop.AjaxForm': ['NodeTypes/*']
    fusion:
      autoInclude:
        'Onedrop.AjaxForm': true
  Flow:
    mvc:
      routes:
        'Onedrop.AjaxForm':
          position: 'start'
